spring:
  profiles.active: dev
  datasource:
    password: ${env.DATABASE_PASSWORD}
    username: ${env.DATABASE_USERNAME}
    url: ${env.DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: strict
logging:
  level:
    org.springframework.security: trace
application:
  csrf-attribute: _csrf
  front-end-url: ${env.FRONT_END_URL}
  allowed-origins: ${env.FRONT_END_URL}
  login-success-url: ${env.FRONT_END_URL}/